Parameters:
    MyBucketName:
        Description: Name of the S3 bucket created
        Type: String

Resources:
    WebsiteBucket:
        Type: AWS::S3::Bucket
        Properties:
            AccessControl: PublicRead
            BucketName: !Sub "${MyBucketName}"
            WebsiteConfiguration:
                ErrorDocument: error.html
                IndexDocument: index.html
    WebsiteBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref WebsiteBucket
            PolicyDocument:
                Statement:
                  - Action: s3:GetObject
                    Effect: Allow
                    Principal: '*'
                    Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]